import Head from 'next/head'
import useSWR from 'swr'
import Shoe from '../components/shoe'
import WizardForm from './WizardForm/index'

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Home() {
    const { data, error } = useSWR('/api/shoes', fetcher)

    if (error) return <div>Failed to load</div>
    if (!data) return <div>Loading...</div>

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <header>
                    <img className='hero-img' src='https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1131&q=80' alt='' />
                </header>
                <WizardForm />
                <div>
                    {data.map((p, i) => (
                        <Shoe key={i} shoe={p} />
                    ))}
                </div>
            </>
        </>
    )
}